apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  annotations:
    ownership: atuya
    description: Backend deployment for Yolo application
spec:
  replicas: 2
  selector:
    matchLabels:
      yolo: backend
  template:
    metadata:
      labels:
        yolo: backend
    spec:
      containers:
        - name: backend-container
          image: docker.io/birisi/yolo-api:v1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/yolomy
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
