---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  annotations:
    ownership: atuya
    description: MongoDB StatefulSet for Yolo application
spec:
  serviceName: mongodb
  replicas: 4
  selector:
    matchLabels:
      yolo: mongodb
  template:
    metadata:
      labels:
        yolo: mongodb
    spec:
      containers:
        - name: mongodb
          image: docker.io/mongo:4.0.28-xenial
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_DATABASE
              value: yolomy
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
volumes:
  - name: mongo-data
    persistentVolumeClaim:
      claimName: mongo-pvc
